baseURL = "https://spletni-kavala.github.io/"
theme = 'hugo-bearblog'
title = "Сплетни Кавалы"
author = "spletni-kavala"
languageCode = "ru"
locale = "ru-RU"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Сплетни Кавалы — блог о технологиях и не только"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Сплетни Кавалы"
  hideMadeWithLine = true

[[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Посты"
  url = "/blog/"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
